name-template: 'v$RESOLVED_VERSION ğŸš€'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'ğŸš€ Features'
    label: 'feat'
  - title: 'ğŸ› Bug Fixes'
    label: 'fix'
  - title: 'ğŸ§° Maintenance'
    label: 'chore'
  - title: 'ğŸ§± Build'
    label: 'build'
  - title: 'ğŸš¥ Continuous Integration'
    label: 'ci'
  - title: 'ğŸ“— Documentation'
    label: 'docs'
  - title: 'ğŸš… Performance'
    label: 'perf'
  - title: 'ğŸ“ Refactor'
    label: 'refactor'
  - title: 'ğŸ’… Style'
    label: 'style'
  - title: 'ğŸ§ª Test'
    label: 'test'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'MAJOR'
  minor:
    labels:
      - 'MINOR'
  patch:
    labels:
      - 'PATCH'
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
references:
  - main
  - v.+
